# Edit this configuration to match your system. Currently every one of
# these but LD is used directly, but you might as well be complete.

DREAM_LIBS= -ltsunami -lparallax -lpng -ljpeg -lkmg -lz -lkosutils -lm -Wl,--gc-sections
CC=kos-cc
CXX=kos-c++
LD=kos-ld
AS=kos-as
AR=kos-ar
OBJCOPY=$(KOS_OBJCOPY)


