# Edit this configuration to match your system. Currently every one of
# these but LD is used directly, but you might as well be complete.

DREAM_CFLAGS=$(KOS_CFLAGS) --fast-math
DREAM_CPPFLAGS=$(KOS_CPPFLAGS)
DREAM_LIBS= -ltsunami -lparallax -lpng -ljpeg -lkmg -lz -lkosutils -lm -Wl,--gc-sections
DREAM_LDFLAGS=$(KOS_LDFLAGS) $(KOS_LIB_PATHS) $(DREAM_LIBS)
CC=kos-cc
CXX=kos-c++
LD=kos-ld
AS=kos-as
AR=kos-ar
OBJCOPY=$(KOS_OBJCOPY)


