# Edit this configuration to match your system. Currently every one of
# these but LD is used directly, but you might as well be complete.

DREAM_CFLAGS=-O2 -fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections -D_arch_dreamcast -D_arch_sub_pristine -Wall -s --fast-math
DREAM_LDFLAGS=-ml -m4-single-only -Wl,-Ttext=0x8c010000
DREAM_LIBS= -lpng -ljpeg -lkmg -lz -lkosutils -lm -Wl,--gc-sections
CC=$(KOS_CC)
CXX=$(KOS_CCPLUS)
LD=$(KOS_LD)
AS=$(KOS_AS)
AR=$(KOS_AR)
OBJCOPY=$(KOS_OBJCOPY)


